### ISSUE TITLE
no pn532 reader with new connected launchpad 

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/acnode-cl#15]
With a new connected launchpad the pn532 reader dosn't get initialised and the code hangs.

If you comment out all the stuff that calls the card reader, get to the cli, set a nodeid and save the settings the board can then talk to the card reader.

I have no idea why this happens :frowning: :confounded: :confused:

**Comment by UKTamo** [comment]
Seems like new boards are Rev D that don't like working...

**Comment by UKTamo** [comment]
Doesn't appear to be bringing the Tx line unto 3v3
