### ISSUE TITLE
Add watchdog timer in case of crashes

### ISSUE THREAD

**Issue by russss** [londonhackspace/acnode-cl#17]

**Comment by JasperWallace** [comment]
http://forum.stellarisiti.com/topic/587-watchdog/
https://github.com/yuvadm/tiva-c/blob/master/boards/ek-lm4f232/watchdog/watchdog.c
https://github.com/energia/Energia/blob/master/hardware/lm4f/cores/lm4f/driverlib/watchdog.h
https://github.com/energia/Energia/blob/master/hardware/lm4f/cores/lm4f/driverlib/watchdog.c
