### ISSUE TITLE
Putting tool out of order in Database does not put tool out of order at ACNode

### ISSUE THREAD

**Issue by UKTamo** [londonhackspace/acnode-cl#23]
I put the Lasercutter out of order in the tools database (setting status to 0), however the tool did not reflect this, even after a user popping their card on the reader. User had to mark as out of order via menu system.

**Comment by JasperWallace** [comment]
there is no way to push status changes to an acnode from the server, so taking the tool out of service from the node is the preferred way.

I can easily add checking the tool status when a card is put on the acnode and before activating the tool tho.

**Comment by UKTamo** [comment]
I understand you cant push info, but I thought it polled for status every
so often. Can we make it poll every minute instead?

**Comment by JasperWallace** [comment]
ead6d54bed62234c205fb647f28d224b559f47ab fixes this.
