### ISSUE TITLE
syslog logging is less verbose

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/acnode-cl#24]
It used to log:

local0.notice<133>: Jan 11 15:12:26 LaserCutter Tool On for 042B51BA5A1E80
local0.notice<133>: Jan 11 15:25:47 LaserCutter Tool off after running for 00:13:20 for 042B51BA5A1E80
local0.notice<133>: Jan 11 15:25:47 LaserCutter Total run time now: 00:13:20

but now just logs:

local0.notice<133>: Jan 12 14:34:22 LaserCutter Tool switched on for 04701E52E72280

The 'off'  and 'total run time' lines have got lost for some reason :disappointed:

**Comment by UKTamo** [comment]
That's because tool time is done via the optothingy on the lasercutter

**Comment by russss** [comment]
Yeah, we moved the time logging back to coolbot to try and debug the
crashing. We can probably put it back now that we know the new code wasn't
at fault.

**Comment by JasperWallace** [comment]
ok, so not a bug
