### ISSUE TITLE
Add a heartbeat

### ISSUE THREAD

**Issue by marksteward** [londonhackspace/acnode-cl#25]
So we can see when the client dies, and catch failed "Access Finished" requests, so should probably include the "in-use" flag.

**Comment by JasperWallace** [comment]
calling a uri on the acserver?

I can add a heartbeat eaisly with an Every().

**Comment by marksteward** [comment]
Yeah! Like /ping or /heartbeat or summat. Happy to add the server-side

**Comment by UKTamo** [comment]
Can we tie this into the ACNode checking acserver for status, and if the DB
says out of service, and the node says in service, the DB wins?

**Comment by marksteward** [comment]
Yeah, maybe we should just call networkCheckToolStatus every minute. If the server doesn't see 3 requests in a row, it assumes the tool's no longer in use?

**Comment by JasperWallace** [comment]
ead6d54bed62234c205fb647f28d224b559f47ab (and 972cccbbdfe9c13b47bd7feb1c9dbf3db78bf578) ended up calling networkCheckToolStatus every 2 seconds.

I can make that longer if needed, but part of that change was that we wanted a way to shut down a tool remotely, potentially in a hurry...

**Comment by UKTamo** [comment]
Why an I getting these

**Comment by JasperWallace** [comment]
On 10 May 2015 01:41:14 BST, UKTamo <notifications@github.com> wrote:
>Why an I getting these 
>
>
>
>> On 10 May 2015, at 01:37, Jasper Wallace <notifications@github.com>
>wrote:
>> 
>> Closed #25.
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/londonhackspace/acnode-cl/issues/25#issuecomment-100567111

You opened the bug originally, so github assumes you want to read the replies, I'm not sure if it possible to reassign a bug to someone else...


--

**Comment by Jonty** [comment]
You can unsubscribe from the thread by hitting the "unwatch" button on the right.

**Comment by UKTamo** [comment]
Ta
