### ISSUE TITLE
trained user who is no longer a member

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/acnode-cl#26]
double check what happens

(16:17:06) solexious: [01:13:34 25] mentar: oh, do you mean the orange is hard to do?
(16:17:06) mentar: [01:13:49 25] Acserver only knows about people who are members
(16:17:06) solexious: [01:13:59 25] I meant the acnode actually did that
(16:17:06) mentar: [01:14:00 25] A person who has not paid is not a member
(16:17:06) mentar: [01:14:20 25] Oh what?!
(16:17:06) solexious: [01:14:44 25] the person was trained but not paid up and it went orange
(16:17:06) mentar: [01:14:54 25] Maybe that's a change jasperw put in in the latest fw version
(16:17:06) solexious: [01:15:05 25] maybe :)
(16:17:06) mentar: [01:15:19 25] Maybe he/she was in the cache but when checked against the backend turns out they weren't a member
(16:17:06) solexious: [01:20:50 25] sounds likely, was just surprising/confusing at the time :)
(

**Comment by JasperWallace** [comment]
So, what was this about again?

If someone stops being a member they can't use tools.

A maintainer _can_ add a card for a registered member who is not paid up, but the card won't work.

**Comment by zymurgic** [comment]
There was an issue whereby if the cache was on sdcard or eeprom, that they would never expire. This has been fixed. There's now a regular verify process for anything still in the cache, to confirm if the cards are still in good standing, both for acnodes and doorbots.
