### ISSUE TITLE
work out what extra hardware we need and add them.

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/acnode-cl#3]
- RGB led?
- Reset button?
- Other button(s)? (e.g. "tool has failed button)
- methods of switching mains power on and off, we have an SSR, would be nice to have a range of options for different current draws
- last but not least, a decent enclosure

**Comment by zymurgic** [comment]
Fairly stable set of acnodes has been deployed at Wembley. This ticket is old and can be closed.
