### ISSUE TITLE
Front Doorbot showing non-member as having opened the door. 

### ISSUE THREAD

**Issue by padski** [londonhackspace/acnode-cl#42]
Note :door does not open.

**Comment by JasperWallace** [comment]
Hi,

Do you have one of the usernames? if so i can trace the card -> user id and then see whats happening...

**Comment by padski** [comment]
Shuvarek

**Comment by JasperWallace** [comment]
it's here: https://github.com/londonhackspace/acnode-cl/compare/doorbot#diff-7bb47dba234158f50917fa69763e3e0fR284

**Comment by zymurgic** [comment]
The announcer used to not differentiate between door opened for a user and a known card that was denied in the annoucements. Now with mqtt, we announce a field 'granted', which can be used by listeners to better determine the events.
