### ISSUE TITLE
EEPROM-backed cache fills up and overwrites the configuration

### ISSUE THREAD

**Issue by jasiek** [londonhackspace/acnode-cl#47]
After a certain amount of time (1-2 months), the cache in the EEPROM fills up to a point where it appears to be overwriting the configuration, thus rendering the unit inoperable.

**Comment by JasperWallace** [comment]
this was fixed - see issue #21 - we need to do a firmware update on the live acnodes.

**Comment by zymurgic** [comment]
All acnodes have since had firmware updated
