### ISSUE TITLE
Poll the server every minute to determine tool status.

### ISSUE THREAD

**Issue by jasiek** [londonhackspace/acnode-cl#52]
Let's say a tool has been remotely enabled again. A reboot is required for the ACNode to pick up this change. It would be far easier if we polled the server for status once a minute, provided that the tool is not in use.

**Comment by JasperWallace** [comment]
I think it does that already when a card is put on the reader?:

https://github.com/londonhackspace/acnode-cl/blob/master/src/acnode.cpp#L375

ah, it needs to be moved outside of the maintainer check.

See also: https://github.com/londonhackspace/acnode-cl/issues/25 and https://github.com/londonhackspace/acnode-cl/issues/23

iirc we don't do the poll once a minute thing cos if the network is down it will hang for 60 seconds, so it only checks when there is a card.

Thought I think we fixed or changed the network timeout?

**Comment by jasiek** [comment]
Right, but if it only gets checked when there's a card present, people will think it is down. The thought behind this is if we flip it on the server remotely (sometimes people put the laser cutter out of service by mistake), we'd like that to be reflected on the laser cutter acnode.

**Comment by jasiek** [comment]
I think the timeout on the http client is one second atm, so it will hang for at most one second, which I think is acceptable.

**Comment by zymurgic** [comment]
I did some work on the polling. It was polling during idle states, every time did a loop, which meant lots of network traffic. I reduced this to every 30 seconds, which is sufficient for remotely re-enabling / disabling of tools. Will deploy on all acnodes today.
