### ISSUE TITLE
Persistent Cache of Maintainers

### ISSUE THREAD

**Issue by mich181189** [londonhackspace/acnode-cl#62]
When a doorbot (or other node using RAM caching) reboots, it loses the cache. This is bad, since it makes fixing issues very hard when the fault is behind a locked door.

The proposal is to sync a subset of users (maintainers, trustees, maybe other common users) to the EEPROM of the node, so even if the node loses all connectivity, these users will still have access.

This obviously assumes the node is not stuck in a reboot loop, but that's a separate issue.

**Comment by zymurgic** [comment]
a meta-cache class that would include two different types of existing caches, and farm out queries to both cache backends), and updates to appropriate backends is probably a good way of achieving this.
That way, maintainers can be stored on eepromcache, regular users in ramcache.
verify() method would need to check that entries are still stored in an appropriate cache backend should they move from regular user to maintainer or vice-versa.

**Comment by mich181189** [comment]
Hmm, I was imagining something simpler where the two caches are maintained largely independently, and the eepromcache is read only to the main caching logic, and there's a separate bit of logic to maintain it - this means the eepromcache doesn't require any special logic, and most of the caching doesn't need to know about the concept of maintainers.

When someone ceases to be a maintainer, I don't see why they need to be immediately added to the RAM cache, likewise, I don't see why users should be removed from the ram cache if they appear in the maintainer cache. The regular RAM cache layer would then take care of this transparently.

**Comment by mich181189** [comment]
After a detour to look at card readers, I'm working on finishing this one off. The good news is it'll no doubt include implementing #66, the bad news is it'll take a little longer than I had first hoped since I basically need to rewrite a bunch of the networking code to support this feature properly.

**Comment by mich181189** [comment]
This is now implemented and deployed to a couple of doors (and one tool, although it doesn't do much there) for testing.

Closing pending deployment more widely.
