### ISSUE TITLE
Unexplained hang of 1st floor dootbot

### ISSUE THREAD

**Issue by zymurgic** [londonhackspace/acnode-cl#64]
Power was good to launchpad. 4.65V at VBUS should be good enough.
No response to card reader, or doorbell
No response to serial console.
No repsonse to ICMP.
Reset button fixed it.

**Comment by mich181189** [comment]
4.65 sounds a little marginal to me. The microcontroller can, no doubt, handle it fine considering it's a 3.3v part, but I wonder how the board overall deals with it?

**Comment by mich181189** [comment]
Launchpad is specified for 4.75-5.25v (source: http://www.ti.com/lit/ug/spmu365c/spmu365c.pdf section 1.6)

**Comment by zymurgic** [comment]
will replace the regulator next time I'm in if nobody gets there sooner.

**Comment by mich181189** [comment]
Power supply was out of spec - closing this one since it’s otherwise too vague to work on
